# Generated by Django 5.2.1 on 2025-05-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(),
        ),
    ]
